deployment:
  resources:
    limits:
      memory: 1G
      cpu: "250m"
    requests:
      memory: 250m
      cpu: "100m"       
database:       
  nodePort: 32000
  replicas: 1

statefulset:
  name: mysql-statefulset-dev

PersistentVolume:
  metadata:
    name: mysql-pv-dev
  claimRef:
    name: mysql-data-mysql-statefulset-dev-0
    namespace: retrosync-dev