deployment:
  resources:
    limits:
      memory: 1G
      cpu: "250m"
    requests:
      memory: 250m
      cpu: "100m"       
database:
  nodePort: 32002
  replicas: 3

statefulset:
  name: mysql-statefulset-prod

PersistentVolume:
  metadata:
    name: mysql-pv-prod
  claimRef:
    name: mysql-data-mysql-statefulset-prod-0
    namespace: retrosync-prod