apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: fastapi-container
        image: tobsss/api-preprod:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: mysql-variables
        resources:
          limits:
            memory: {{ .Values.deployment.resources.limits.memory}}
            cpu: {{ .Values.deployment.resources.limits.cpu}}
          requests: 
            memory: {{ .Values.deployment.resources.requests.memory}}
            cpu: {{ .Values.deployment.resources.requests.cpu}}