apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name}}
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            namespaces: 
            - retrosync-dev
            - retrosync-preprod
            - retrosync-prod
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - api-server
            topologyKey: "kubernetes.io/hostname"
        containers:
      - name: mysql
        image: {{ .Values.version.database.name }}:{{ .Values.version.database.tag }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-variables
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-variables
              key: MYSQL_DB
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: {{ .Values.deployment.resources.limits.memory}}
            cpu: {{ .Values.deployment.resources.limits.cpu}}
          requests: 
            memory: {{ .Values.deployment.resources.requests.memory}}
            cpu: {{ .Values.deployment.resources.requests.cpu}}
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
        