apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.PersistentVolume.metadata.name}}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: {{ .Values.PersistentVolume.claimRef.name}}
    namespace: {{ .Values.PersistentVolume.claimRef.namespace}}
  hostPath:
    path: /mnt/data # Specify a path in the host for storage