apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: preproduction
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-MYSQL_ROOT_PASSWORD: "secret/MYSQL_ROOT_PASSWORD"
        vault.hashicorp.com/agent-inject-template-my-first-secret: |
          {{- with secret "secret/my-first-secret" -}}
          MYSQL_ROOT_PASSWORD={{ .Data.data.MYSQL_ROOT_PASSWORD }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
      - image: mysql:8.2
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: preproduction
spec:
  ports:
  - port: 3306
  selector:
    app: mysql