apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: preproduction
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3306"
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql
      nodePort: 32000
      protocol: TCP
      port: 3306
      targetPort: 3306
