apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: preproduction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: react-app
          image: tobsss/frontend-preprod:v0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000