deployment:
  resources:
    limits:
      memory: 1G
      cpu: "250m"
    requests:
      memory: 250m
      cpu: "100m"       
database:
  nodePort: 32001
  replicas: 1

statefulset:
  name: mysql-statefulset-preprod

PersistentVolume:
  metadata:
    name: mysql-pv-preprod
  claimRef:
    name: mysql-data-mysql-statefulset-preprod-0
    namespace: retrosync-preprod