{
 "title": "Kubernetes Pod Dashboard",
 "description": "Dashboard for kubernetes pod",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-kube_pod_start_time{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$duration])))"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$duration])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Memory(%)"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$duration])) ",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Resource Request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Resource Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory (Swap/Hits Limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{namespace=\"$namespace\"}[$duration]))",
     "legendFormat": "Hits limits"
    }
   ]
  },
  {
   "title": "Out of Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(round(increase(container_oom_events_total{namespace=\"$namespace\"}[$duration])))",
     "legendFormat": "OOM"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$duration]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$duration]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Number of Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\"})",
     "legendFormat": "Thread"
    }
   ]
  }
 ]
}