apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: preproduction
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: fastapi-container
        image: tobsss/api-preprod:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mysql-variables