apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: preproduction
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32020
  type: NodePort