apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retrosync-preprod
spec:
  destination:
    namespace: retrosync-preprod
    server: https://kubernetes.default.svc
  source:
    path: infrastructure
    repoURL: https://github.com/tob-ss/retrosync
    targetRevision: new_main
    helm:
      valueFiles:
        - environments/preprod/api/values.yaml
        - environments/preprod/api/version.yaml
        - environments/preprod/database/values.yaml
        - environments/preprod/database/version.yaml
        - environments/preprod/frontend/values.yaml
        - environments/preprod/frontend/version.yaml
        - environments/preprod/management/values.yaml
        - environments/preprod/management/version.yaml
  sources: []
  project: retrosync
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true