name: Deploy to Server

on:
  push:
    branches:
      - feat/phase2-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: "Configure SSH"
      env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/external-machine.key
          chmod 600 ~/.ssh/external-machine.key
          cat >>~/.ssh/config <<END
          Host external-machine
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/external-machine.key
            StrictHostKeyChecking no
          END
    - name: Deploy to server
      run: |
        echo "Starting deployment.."
        echo "SSHing into server"
        ssh external-machine << EOF
          echo "Moving to retrosync directory"
          cd retrosync/retrosync

          # Set GitHub credentials using GITHUB_TOKEN
          echo "Setting Github Credentials"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" > ~/.git-credentials

          # Pull the latest code from the repository
          echo "Pulling code"
          git pull origin feat/phase2-frontend

          # Docker compose down
          echo "Docker compose down"
          docker compose down

          # Docker compose build
          echo "Docker compose build"
          docker compose build

          # Docker compose up
          echo "Docker compose up"
          docker compose up -d
        echo "Finished deployment!"
        EOF
